name: C++ CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make

    # Configure the project with CMake
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake ..

    # Build the project
    - name: Build with Make
      run: |
        cd build
        make

    # Run tests (if applicable)
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure